# Generated by Django 5.2.5 on 2025-11-04 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Mot-clé')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('category', models.CharField(choices=[('general', 'Général'), ('symptoms', 'Symptômes'), ('services', 'Services'), ('emergency', 'Urgences'), ('medication', 'Médicaments'), ('appointment', 'Rendez-vous'), ('other', 'Autre')], default='general', max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Entrée de base de connaissances',
                'verbose_name_plural': 'Entrées de base de connaissances',
                'db_table': 'ChatbotKnowledgeBase',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_constante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Constante',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('notes_chiffrees', models.TextField(blank=True, verbose_name='Notes chiffrées')),
                ('diagnostic_chiffre', models.TextField(blank=True, verbose_name='Diagnostic chiffré')),
            ],
            options={
                'db_table': 'Consultation',
            },
        ),
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dentiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Medicament',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ouvert_24h', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureDeSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField()),
            ],
            options={
                'db_table': 'StructureDeSante',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('read', 'Lecture'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export de données')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'db_table': 'AuditLog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sante_app.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de consultation',
                'verbose_name_plural': 'Messages de consultation',
                'db_table': 'ConsultationMessage',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilite', models.BooleanField(default=True)),
                ('specialite', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Medecin',
            },
        ),
        migrations.CreateModel(
            name='IndisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type', models.CharField(choices=[('conges', 'Congés'), ('formation', 'Formation'), ('maladie', 'Maladie'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('toute_la_journee', models.BooleanField(default=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='sante_app.medecin')),
            ],
            options={
                'verbose_name': 'Indisponibilité Médecin',
                'verbose_name_plural': 'Indisponibilités Médecins',
                'db_table': 'IndisponibiliteMedecin',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='sante_app.medecin'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('resume', models.TextField(max_length=500, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('categorie', models.CharField(choices=[('prevention', 'Prévention'), ('nutrition', 'Nutrition'), ('maladies', 'Maladies'), ('bien_etre', 'Bien-être'), ('grossesse', 'Grossesse'), ('pediatrie', 'Pédiatrie'), ('geriatrie', 'Gériatrie'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('desactive', 'Désactivé')], default='brouillon', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_moderation', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vues', models.IntegerField(default=0)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_valides', to=settings.AUTH_USER_MODEL)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sante_app.medecin')),
            ],
            options={
                'verbose_name': 'Article de Santé',
                'verbose_name_plural': 'Articles de Santé',
                'db_table': 'Article',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sante_app.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id_mesure', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
                ('constante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='sante_app.constante')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article_valide', 'Article validé'), ('article_refuse', 'Article refusé'), ('article_desactive', 'Article désactivé')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('article_titre', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sante_app.medecin')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('medecins', models.ManyToManyField(related_name='pathologies', to='sante_app.medecin')),
                ('patients', models.ManyToManyField(related_name='pathologies', to='sante_app.patient')),
            ],
            options={
                'db_table': 'Pathologie',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='sante_app.patient'),
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user', models.TextField(verbose_name='Message utilisateur')),
                ('message_bot', models.TextField(verbose_name='Réponse chatbot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sentiment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='sante_app.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RappelMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100, verbose_name='Nom du médicament')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('frequence', models.CharField(max_length=50, verbose_name='Fréquence')),
                ('heure_rappel', models.TimeField(verbose_name='Heure du rappel')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Rappel actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_medicaments', to='sante_app.patient')),
            ],
            options={
                'verbose_name': 'Rappel médicament',
                'verbose_name_plural': 'Rappels médicaments',
                'ordering': ['heure_rappel'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePriseMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise', models.DateTimeField(auto_now_add=True, verbose_name='Date de prise')),
                ('prise_effectuee', models.BooleanField(default=False, verbose_name='Prise effectuée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('rappel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prises', to='sante_app.rappelmedicament')),
            ],
            options={
                'verbose_name': 'Historique prise médicament',
                'verbose_name_plural': 'Historiques prises médicaments',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('motif_consultation', models.TextField(blank=True, help_text='Motif de la consultation', null=True)),
                ('type_consultation', models.CharField(choices=[('cabinet', 'Consultation au cabinet'), ('teleconsultation', 'Téléconsultation en ligne')], default='cabinet', max_length=20)),
                ('statut', models.CharField(choices=[('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('RESCHEDULED', 'Reprogrammé'), ('PENDING', 'En attente'), ('TERMINE', 'Terminé')], default='PENDING', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_heure', models.TimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RendezVous',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='medical_documents/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sante_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'db_table': 'MedicalDocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sante_app.rendezvous'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sante_app.structuredesante')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultation', to='sante_app.consultation')),
            ],
            options={
                'db_table': 'Teleconsultation',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id_traitement', models.AutoField(primary_key=True, serialize=False)),
                ('posologie', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='sante_app.consultation')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='sante_app.medicament')),
            ],
            options={
                'db_table': 'Traitement',
            },
        ),
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_urgence', models.CharField(max_length=100, verbose_name="Type d'urgence")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('symptomes', models.TextField(verbose_name='Symptômes')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('priorite_automatique', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], max_length=20)),
                ('score_urgence', models.IntegerField(default=0, help_text='Score calculé automatiquement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prise_en_charge', 'Prise en charge'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('personne_contact', models.CharField(blank=True, max_length=100, verbose_name='Nom de la personne à contacter')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes_medecin', models.TextField(blank=True, verbose_name='Notes du médecin')),
                ('medecin_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgences_prises_en_charge', to='sante_app.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgences', to='sante_app.patient')),
            ],
            options={
                'verbose_name': 'Urgence',
                'verbose_name_plural': 'Urgences',
                'db_table': 'Urgence',
                'ordering': ['-priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_urgences', to='sante_app.medecin')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sante_app.urgence')),
            ],
            options={
                'verbose_name': 'Notification Urgence',
                'verbose_name_plural': 'Notifications Urgences',
                'db_table': 'NotificationUrgence',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_consultation', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('pause_dejeuner_debut', models.TimeField(blank=True, null=True)),
                ('pause_dejeuner_fin', models.TimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='sante_app.medecin')),
            ],
            options={
                'unique_together': {('medecin', 'jour')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sante_app.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sante_app.patient')),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='sante_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'db_table': 'Rating',
                'ordering': ['-date_creation'],
                'unique_together': {('patient', 'rendez_vous')},
            },
        ),
    ]
