# Generated by Django 5.2.5 on 2025-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0002_zoomtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
