# Generated by Django 5.2.5 on 2025-11-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0003_rendezvous_zoom_join_url_rendezvous_zoom_start_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
