# Generated by Django 5.2.5 on 2025-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0004_rendezvous_zoom_meeting_id_rendezvous_zoom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='zoom_join_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='zoom_start_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
