# Generated by Django 5.2.5 on 2025-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0005_alter_rendezvous_zoom_join_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.CharField(default='Bonjour {user}! 👋 Je suis votre assistant virtuel.', max_length=255)),
                ('input_placeholder', models.CharField(default='Écrivez un message ici...', max_length=100)),
                ('placeholder_text', models.CharField(default='Rechercher...', max_length=100)),
                ('primary_color', models.CharField(default='#22c55e', max_length=7)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('fallback_message', models.CharField(default='Désolé, je n’ai pas compris.', max_length=255)),
            ],
        ),
    ]
