# Generated by Django 5.2.5 on 2025-11-09 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0006_chatbotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='confidence_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='fallback_message',
            field=models.CharField(default="Je n'ai pas compris.", max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='input_placeholder',
            field=models.CharField(default='Écrire un message Ici...', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='placeholder_text',
            field=models.CharField(default='Rechercher...', max_length=255),
        ),
    ]
