# Generated by Django 5.2.5 on 2025-11-10 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0007_chatbotconfig_updated_at_chatbotconfig_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequence', models.CharField(default='1/jour', max_length=20)),
                ('heure_rappel', models.TimeField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sante_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise', models.DateTimeField(default=django.utils.timezone.now)),
                ('taken', models.BooleanField(default=False)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sante_app.medicationreminder')),
            ],
        ),
    ]
