# Generated by Django 5.2.5 on 2025-11-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0008_medicationreminder_medicationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='dosage',
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='date_fin',
            field=models.DateField(default='2025-11-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante_app.medicament'),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante_app.patient'),
        ),
    ]
