# Generated by Django 5.2.5 on 2025-11-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0009_remove_medicationreminder_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilitemedecin',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='MedicationHistory',
        ),
        migrations.DeleteModel(
            name='MedicationReminder',
        ),
    ]
