# Generated by Django 5.2.5 on 2025-11-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0010_remove_medicationreminder_medicament_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilitemedecin',
            unique_together={('medecin', 'jour')},
        ),
    ]
