# Generated by Django 5.2.5 on 2025-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0011_alter_disponibilitemedecin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='nom_patient',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du patient'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='poids',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='prenom_patient',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom du patient'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='taille',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
