# Generated by Django 5.2.5 on 2025-11-14 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0012_medicaldocument_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante_app.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante_app.patient')),
            ],
        ),
    ]
